// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: modelData.proto
// Protobuf C++ Version: 5.27.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_modelData_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_modelData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "meshData.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_modelData_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_modelData_2eproto {
  static const ::uint32_t offsets[];
};
class modelData_proto;
struct modelData_protoDefaultTypeInternal;
extern modelData_protoDefaultTypeInternal _modelData_proto_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class modelData_proto final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:modelData_proto) */ {
 public:
  inline modelData_proto() : modelData_proto(nullptr) {}
  ~modelData_proto() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR modelData_proto(
      ::google::protobuf::internal::ConstantInitialized);

  inline modelData_proto(const modelData_proto& from) : modelData_proto(nullptr, from) {}
  inline modelData_proto(modelData_proto&& from) noexcept
      : modelData_proto(nullptr, std::move(from)) {}
  inline modelData_proto& operator=(const modelData_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline modelData_proto& operator=(modelData_proto&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const modelData_proto& default_instance() {
    return *internal_default_instance();
  }
  static inline const modelData_proto* internal_default_instance() {
    return reinterpret_cast<const modelData_proto*>(
        &_modelData_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(modelData_proto& a, modelData_proto& b) { a.Swap(&b); }
  inline void Swap(modelData_proto* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(modelData_proto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  modelData_proto* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::MessageLite::DefaultConstruct<modelData_proto>(arena);
  }
  void CheckTypeAndMergeFrom(
      const ::google::protobuf::MessageLite& from) final;
  void CopyFrom(const modelData_proto& from);
  void MergeFrom(const modelData_proto& from);
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(modelData_proto* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "modelData_proto"; }

 protected:
  explicit modelData_proto(::google::protobuf::Arena* arena);
  modelData_proto(::google::protobuf::Arena* arena, const modelData_proto& from);
  modelData_proto(::google::protobuf::Arena* arena, modelData_proto&& from) noexcept
      : modelData_proto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData() const final;

 public:
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMeshesFieldNumber = 1,
  };
  // repeated .meshData_proto meshes = 1;
  int meshes_size() const;
  private:
  int _internal_meshes_size() const;

  public:
  void clear_meshes() ;
  ::meshData_proto* mutable_meshes(int index);
  ::google::protobuf::RepeatedPtrField<::meshData_proto>* mutable_meshes();

  private:
  const ::google::protobuf::RepeatedPtrField<::meshData_proto>& _internal_meshes() const;
  ::google::protobuf::RepeatedPtrField<::meshData_proto>* _internal_mutable_meshes();
  public:
  const ::meshData_proto& meshes(int index) const;
  ::meshData_proto* add_meshes();
  const ::google::protobuf::RepeatedPtrField<::meshData_proto>& meshes() const;
  // @@protoc_insertion_point(class_scope:modelData_proto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_modelData_proto_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const modelData_proto& from_msg);
    ::google::protobuf::RepeatedPtrField< ::meshData_proto > meshes_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_modelData_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// modelData_proto

// repeated .meshData_proto meshes = 1;
inline int modelData_proto::_internal_meshes_size() const {
  return _internal_meshes().size();
}
inline int modelData_proto::meshes_size() const {
  return _internal_meshes_size();
}
inline ::meshData_proto* modelData_proto::mutable_meshes(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:modelData_proto.meshes)
  return _internal_mutable_meshes()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::meshData_proto>* modelData_proto::mutable_meshes()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:modelData_proto.meshes)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_meshes();
}
inline const ::meshData_proto& modelData_proto::meshes(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:modelData_proto.meshes)
  return _internal_meshes().Get(index);
}
inline ::meshData_proto* modelData_proto::add_meshes() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::meshData_proto* _add = _internal_mutable_meshes()->Add();
  // @@protoc_insertion_point(field_add:modelData_proto.meshes)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::meshData_proto>& modelData_proto::meshes() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:modelData_proto.meshes)
  return _internal_meshes();
}
inline const ::google::protobuf::RepeatedPtrField<::meshData_proto>&
modelData_proto::_internal_meshes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.meshes_;
}
inline ::google::protobuf::RepeatedPtrField<::meshData_proto>*
modelData_proto::_internal_mutable_meshes() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.meshes_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_modelData_2eproto_2epb_2eh
