// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: modelData.proto
// Protobuf C++ Version: 5.27.2

#include "modelData.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr modelData_proto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : meshes_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR modelData_proto::modelData_proto(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct modelData_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR modelData_protoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~modelData_protoDefaultTypeInternal() {}
  union {
    modelData_proto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 modelData_protoDefaultTypeInternal _modelData_proto_default_instance_;
// ===================================================================

class modelData_proto::_Internal {
 public:
};

void modelData_proto::clear_meshes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.meshes_.Clear();
}
modelData_proto::modelData_proto(::google::protobuf::Arena* arena)
    : ::google::protobuf::MessageLite(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:modelData_proto)
}
inline PROTOBUF_NDEBUG_INLINE modelData_proto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::modelData_proto& from_msg)
      : meshes_{visibility, arena, from.meshes_},
        _cached_size_{0} {}

modelData_proto::modelData_proto(
    ::google::protobuf::Arena* arena,
    const modelData_proto& from)
    : ::google::protobuf::MessageLite(arena) {
  modelData_proto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:modelData_proto)
}
inline PROTOBUF_NDEBUG_INLINE modelData_proto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : meshes_{visibility, arena},
        _cached_size_{0} {}

inline void modelData_proto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
modelData_proto::~modelData_proto() {
  // @@protoc_insertion_point(destructor:modelData_proto)
  _internal_metadata_.Delete<std::string>();
  SharedDtor();
}
inline void modelData_proto::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
modelData_proto::GetClassData() const {
  PROTOBUF_CONSTINIT static const ClassDataLite<16> _data_ =
      {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(modelData_proto, _impl_._cached_size_),
              true,
          },
          "modelData_proto",
      };

  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> modelData_proto::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_modelData_proto_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::modelData_proto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .meshData_proto meshes = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(modelData_proto, _impl_.meshes_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .meshData_proto meshes = 1;
    {PROTOBUF_FIELD_OFFSET(modelData_proto, _impl_.meshes_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::meshData_proto>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void modelData_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:modelData_proto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.meshes_.Clear();
  _internal_metadata_.Clear<std::string>();
}

::uint8_t* modelData_proto::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:modelData_proto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .meshData_proto meshes = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_meshes_size());
       i < n; i++) {
    const auto& repfield = this->_internal_meshes().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:modelData_proto)
  return target;
}

::size_t modelData_proto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:modelData_proto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated .meshData_proto meshes = 1;
  total_size += 1UL * this->_internal_meshes_size();
  for (const auto& msg : this->_internal_meshes()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  _impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void modelData_proto::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const modelData_proto*>(
      &from));
}

void modelData_proto::MergeFrom(const modelData_proto& from) {
  modelData_proto* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:modelData_proto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_meshes()->MergeFrom(
      from._internal_meshes());
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void modelData_proto::CopyFrom(const modelData_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:modelData_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void modelData_proto::InternalSwap(modelData_proto* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.meshes_.InternalSwap(&other->_impl_.meshes_);
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
